### ISSUE TITLE
In the identification of microsynteny genes based on the WGDI algorithm, the data type transfer issue

### ISSUE THREAD

**Issue by HyCipher** [yhw320/PanSyn#7]
Hi, I am trying to identify microsynteny based on the WGDI algorithm. When I run `wgdi -icl wgdi-collinearity.conf`, the error shown in the following picture is generated, the **start** column involves mixed type (int and string). I checked the source code of `base.py` and debug. The attached output.csv file can display columns 2 datatype of Dataframe, representing **start**  column. I found that the second column's data type is a string after row 131073 after I wrote a datatype check code, which will read the output.csv file as Dataframe with pandas.
[test_data.zip](https://github.com/user-attachments/files/16593402/test_data.zip)
![Screenshot 2024-08-13 at 10 45 12](https://github.com/user-attachments/assets/207b510e-8776-461c-b824-d3c1c181aa22)
[output.csv](https://github.com/user-attachments/files/16593439/output.csv)

**Comment by yhw320** [comment]
Hello,
I noticed an issue with the simplified GFF file in your test data. Specifically, it appears that multiple location entries are provided for a single gene, such as NP_001007096.1. 
![1](https://github.com/user-attachments/assets/f16ab2f2-c367-479c-801a-85f4920fe6fd)
This is likely because the longest transcript was not handled properly.

To resolve this issue, I recommend reprocessing the simplified GFF file to ensure that each gene is associated with only one location entry. This should prevent the program from encountering errors related to ambiguous location information.
